### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by randompee** [puuu/ESPiLight#12]
A number of files is missing in the ZIP. Lucky for me I found http://platformio.org/lib/show/996/ESPiLight, which had all the missing files!

**Comment by puuu** [comment]
Thank you for using ESPiLight,
were/how did you downloaded the ZIP file?
The files under [releases](https://github.com/puuu/ESPiLight/releases) should work.
If you downloaded the source files as ZIP from the master branch, than the pilight source files are missing. Please see the README for more details.

**Comment by puuu** [comment]
No answer for long time. Close it. Please reopen if not solved.
