### ISSUE TITLE
json.h file missing, does not compile

### ISSUE THREAD

**Issue by tubalainen** [puuu/ESPiLight#25]
Appointed by the protocol.h file -> #include "../core/json.h" 

json.h does not exist, cannot compile json features using this lib.

`Arduino: 1.8.4 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200, 4M (3M SPIFFS)"

In file included from C:\Users\torbj\Documents\Arduino\libraries\ESPiLight\src\ESPiLight.cpp:35:0:

C:\Users\torbj\Documents\Arduino\libraries\ESPiLight\src\pilight/libs/pilight/protocols/protocol.h:26:26: fatal error: ../core/json.h: No such file or directory

 #include "../core/json.h"

                          ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
`

**Comment by puuu** [comment]
Probably #12 ? Where/how did you got the library? Please install from library manager.

**Comment by tubalainen** [comment]
Indeed, my bad! Thanks, compiles like a charm now!

**Comment by puuu** [comment]
Thanks, for your comment and much fun with ESPiLight.
