### ISSUE TITLE
Library does not work with Uno, Nano, Mega

### ISSUE THREAD

**Issue by chmasi** [puuu/ESPiLight#26]
Hi,
I am not able to use this library with an Uno, Nano or Mega. 
Is this expected?

**Comment by janLo** [comment]
Yes. The library is meant to be used on an ESP8266 or an ESP32.

**Comment by chmasi** [comment]
That's a pity, that would also be a great library for the standard arduinos, is there a plan to make it available for the normal Arduinos?

**Comment by janLo** [comment]
I doubt that it will fit into atmega controllers. It uses on an esp about 14k of heap space. The atmega 328 has 2k ram at all. Also the atmega devices run only on 16mhz while the esp range from 80 to 250 MHz. So even if it fits in the memory I'm not quite sure if it's fast enough.

**Comment by puuu** [comment]
@janLo is correct. ESPiLight use the pilight protocols, a good open source implementation of many 433MHz protocols. But unfortunately, it was not written with micro controller like the AVRs in mind. You are better to go with a more lightweight implementation (see [other similar projects](https://github.com/puuu/ESPiLight#other-similar-projects))  in the README.
