### ISSUE TITLE
New pilight library version integration

### ISSUE THREAD

**Issue by 1technophile** [puuu/ESPiLight#37]
Hello,

Would it be possible to integrate the last version of pilight library (8.1.4) into ESPilight so to takes the benefits of the commits done from the [current integration](https://github.com/pilight/pilight/tree/040e3d863d4e11464e87fb42a1ea7dc184b5c011)?
Or to give the integration process and I could submit a PR.

**Comment by puuu** [comment]
Thank you for pointing to recent pilight changes. Until d45e57947403214cd484c4709a40d7495049e161 I tracked the development branch of pilight, which is now disappeared and seemed to differ from the master branch. Now I change to the staging branch. A [new](https://github.com/puuu/ESPiLight/releases/tag/v0.16.0) release release was created.

**Comment by 1technophile** [comment]
thanks!
