### ISSUE TITLE
Request for a protocol

### ISSUE THREAD

**Issue by YordanYanakiev** [puuu/ESPiLight#40]
Hello.
I have piles of these
https://www.ebay.com/itm/Restaurant-Wireless-Guest-Waiter-Calling-System-2-Receiver-Host-50-Button-Pagers/173181088620?hash=item285265b36c:g:AXUAAOSwTlFak6Xt
and tons of these :
https://www.ebay.com/itm/New-Green-Call-Button-Pagers-for-Wireless-Restaurant-Calling-Paging-Sysatem-HOT/312188912487?hash=item48afe8c367:g:F5QAAOSw65FXrYf5

And I would like to use them with ESPiLight.
Currently testing with RXB6 module, and in raw format seems like I am receiving the data.
The problem is that I have no idea how to parse it into a readable string. I am just not sure about the protocol.
My question is - if You have pass trough such a device or can help me understanding the protocol of these things.

**Comment by puuu** [comment]
Please check the [readme](https://github.com/puuu/ESPiLight/blob/master/README.md). New protocols should be report to the pilight project.
