### ISSUE TITLE
Protocol not supported error

### ISSUE THREAD

**Issue by bn326160** [puuu/ESPiLight#41]
For some of the protocols I receive an ERROR_UNAVAILABLE_PROTOCOL error (result code 0) on sending the commands.

**Tested:**
- elro_400_switch - recognized
- x10 - recognized
- tfa - unrecognized
- sc2262 - unrecognized
- arctech_switch - unrecognized

I don't seem to be able to find the problem as they are listed in protocol_init.h and _sc2262  and arctech_switch_ seem to be recognized on sending the pulses from the remote.

**Comment by puuu** [comment]
Not all protocols implement transmission support. You can check the protocol source files for a `createCode()` function.
