### ISSUE TITLE
ESPiLight::mingaplen too large for the Nexus protocol

### ISSUE THREAD

**Issue by ligius-** [puuu/ESPiLight#44]
I've implemented the Nexus decoder but a change was required in ESPiLight to get it working. Nexus requires 4000us between repeats while ESPiLight overrides this to 5100. This causes the decoder to receive several trains. This could work, but the decoder cannot signal back to the caller that it has received more trains. This means that the main program does not see if a code has been repeated and will not publish it.
I've changed this variable to 3700 locally and it seems to run fine. Not sure how other protocols are affected by this.
Each decoder publishes their own mingaplen but this seems to be ignored. maxgaplen seems to not be used at all.

**Comment by puuu** [comment]
Thanks, good point!

The `mingaplen` in of the protocols should be honoured. I implemented it in 969ab14113f19859e43ce7bc4db69104b30833db. I think it is fine, since pilight does it in a similar way. `maxgaplen` is also not used in pilight.
