### ISSUE TITLE
example 'transmit' using 2nd delay()

### ISSUE THREAD

**Issue by Jekyll555** [puuu/ESPiLight#5]
First of all Thanks! for all the cool code stuff. Got my rc switch controlled in minutes after my RF sender postal arrived... that included internet search to find your lib!
My 2cts: 

  rf.send("elro_800_switch", "{\"systemcode\":17,\"unitcode\":1,\"on\":1}");
  delay(2000);
  rf.send("elro_800_switch", "{\"systemcode\":17,\"unitcode\":1,\"off\":1}");
  delay(2000); //<-- makes that blinking last~

**Comment by ripper121** [comment]
What do you mean with "delay(2000); //<-- makes that blinking last~" please describe it a litte better

**Comment by puuu** [comment]
Thank you for reporting this bug.

Fixed in e6a0dbb5f9d37ec08906623aeb8efd5c79faa534.

Nice to hear that other are using this library.

**Comment by ripper121** [comment]
What have you changed?

**Comment by puuu** [comment]
@ripper121 please have a look to the commit e6a0dbb5f9d37ec08906623aeb8efd5c79faa534. I added the missing delay at the end of the loop in the transmit example.
So, it will be avaiable if I build a new release.
